# permissions for end users to edit backups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backup-editor-role
rules:
- apiGroups:
  - storage.my.domain
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.my.domain
  resources:
  - backups/status
  verbs:
  - get
