apiVersion: storage.my.domain/v1
kind: Restore
metadata:
  labels:
    app.kubernetes.io/name: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: restore-sample
spec:
  # TODO(user): Add fields here
