apiVersion: storage.my.domain/v1
kind: Restore
metadata:
  labels:
    app.kubernetes.io/name: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: restore-sample
spec:
  applicationName: my-app                    # The application name to restore
  storageLocation: backup-operator            # The S3Mock bucket from where the backup will be restored
  backupFile: my-app-backup-1726375690.tar.gz # The specific backup file to be restored
